### ISSUE TITLE
errors after ran webpack

### ISSUE THREAD

**Issue by tranduyduong** [infeng/generator-react-redux-weback-typescript#1]
hi bro,
I have just met the following errors after followed your guide:
ERROR in ./src/js/App.tsx
(1,19): error TS2307: Cannot find module 'react'.

ERROR in ./src/js/App.tsx
(2,27): error TS2307: Cannot find module 'react-dom'.

ERROR in ./src/js/App.tsx
(4,29): error TS2307: Cannot find module 'react-redux'.

ERROR in ./src/js/App.tsx
(9,19): error TS2307: Cannot find module 'redux-thunk'.

ERROR in ./src/js/App.tsx
(23,14): error TS2339: Property 'props' does not exist on type 'HelloWorld'.

ERROR in ./src/js/App.tsx
(28,32): error TS2339: Property 'props' does not exist on type 'HelloWorld'.

ERROR in ./src/js/App.tsx
(29,66): error TS2339: Property 'props' does not exist on type 'HelloWorld'.

ERROR in ./src/js/common/Logger.ts
(2,21): error TS2314: Generic type 'Store<S>' requires 1 type argument(s).

ERROR in ./src/js/appReducer.ts
(13,20): error TS2314: Generic type 'Reducer' requires 1 type argument(s).

please help me to  fix.

thanks

**Comment by infeng** [comment]
@duong i fix the error now,i update the README.md,you should install it again and try again. typings's new version cause this error.at last,my other project https://github.com/infeng/react-typescript-example is better, have a try!

**Comment by tranduyduong** [comment]
@infeng 
Many thank for your quick support, I still have error. This seems I need to install react, react-dom etc via tsd  manually. anyway, I will try the project above and ask you if needed. :)
regards
