### ISSUE TITLE
Error: Cannot find module 'glob'

### ISSUE THREAD

**Issue by teofilusrobert** [infeng/generator-react-redux-weback-typescript#2]
When on step "yo react-redux-typescript", I got this error.
I tried to install glob module using "npm i glob" but still get same error:

> Error: Cannot find module 'glob'
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (C:\Users\FORMULATRIX\AppData\Roaming\npm\node_modules\generator-react-redux-typescript\generators\app\
> index.js:4:12)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)

Any clue what I miss?

**Comment by infeng** [comment]
I run `yo react-redux-typescript`, it works well. Try uninstall `yo` `generator-react-redux-typescript` and reinstall them.
In the end, I recommend to use [inf-fed-dev](https://github.com/infeng/inf-fed-dev).
